_format_version: "3.0"
_transform: true
 
services:
  - name: quote-service
    url: http://quotes:8080
    routes:
      - name: quote-service-routes
        paths:
          - /mock-34
        strip_path: true
 
plugins:
      - name: rate-limiting
        config:
          minute: 5
          policy: redis
          redis_host: redis
          redis_port: 6379
